cleaned up logging

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -9,14 +9,6 @@ fi
 
 my_config="
 global
-	log /dev/log	local0
-	log /dev/log	local1 notice
-	chroot /var/lib/haproxy
-	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
-	stats timeout 30s
-	user haproxy
-	group haproxy
-
 	daemon
 	maxconn 256
 
@@ -25,17 +17,6 @@ defaults
 	timeout connect 5s
 	timeout client 50s
 	timeout server 50s
-	log	global
-	option	httplog
-	option	dontlognull
-	errorfile 400 /etc/haproxy/errors/400.http
-	errorfile 403 /etc/haproxy/errors/403.http
-	errorfile 408 /etc/haproxy/errors/408.http
-	errorfile 500 /etc/haproxy/errors/500.http
-	errorfile 502 /etc/haproxy/errors/502.http
-	errorfile 503 /etc/haproxy/errors/503.http
-	errorfile 504 /etc/haproxy/errors/504.http
-
 
 frontend frontends
 	bind *:80
@@ -45,11 +26,15 @@ backend backends
 	balance roundrobin
 	server web-01 54.144.238.161 check
 	server web-02 100.25.154.52 check
-	"
+"
 
 echo -e "$my_config" | sudo tee /etc/haproxy/my_config.cfg > /dev/null
 
-sudo haproxy -c -f /etc/haproxy/my_config.cfg
+
+if  ! sudo haproxy -c -f /etc/haproxy/my_config.cfg ; then
+    echo "Error: HAProxy configuration check failed. Please fix the configuration."
+    exit 1
+fi
 
 sudo systemctl start haproxy
 sudo systemctl enable haproxy
